### ISSUE TITLE
Sugestões do Hurick

### ISSUE THREAD

**Issue by hurickkrugner-luizalabs** [juninmd/apresentacao-desenvolvimento-hibrido#1]
Nessa issue irei agrupar tudo o que eu acredito ser sugestões válidas para sua apresentação.
Peço apenas que não comente até eu finalizar as anotações (avisarei em um post de fechamento), para manter a organização da issue em si.

Valeu!
(E espero que ajude de algo 👊🏻)

**Comment by hurickkrugner-luizalabs** [comment]
### Slide #02

![image](https://user-images.githubusercontent.com/30271766/35042254-0531e7c4-fb6f-11e7-912e-633b42b39e87.png)

- **Desenvolvedor**: Desenvolvedor o que? Entendo que esteja apresentando isso pro Labs e provavelmente muita gente vai saber o que você faz aqui, e que é um desenvolvedor. Mas tente imaginar se estivesse apresentando em uma conferência. Não acha que seria legal ler o seu título completo? **Ex.: Backend Developer, Frontend Developer, Full Stack Developer, etc.**

- **Solteiro**: Não acredito que seja uma informação relevante pro que vai apresentar, sabe? É tipo você estar procurando vaga de emprego na área de desenvolvimento e dizer que tem experiência profissional como cozinheiro. Do que vale a informação?

**Comment by hurickkrugner-luizalabs** [comment]
### Slide #08

![image](https://user-images.githubusercontent.com/30271766/35042492-17956138-fb70-11e7-97dd-ae4e4aa8e2af.png)

- **Hibrído**: Na verdade o acento é no primeiro "i", ou seja, **Híbrido**.

**Comment by hurickkrugner-luizalabs** [comment]
### Slide #09

![image](https://user-images.githubusercontent.com/30271766/35042549-498083c6-fb70-11e7-8647-f71efc38f98b.png)

- **Hibrido**: Aqui você resolveu ficar puto com tudo e não quis acentuar. Não se esqueça: **Híbrido**.

**Comment by hurickkrugner-luizalabs** [comment]
### Slide #11

![image](https://user-images.githubusercontent.com/30271766/35042613-8ac3f5d4-fb70-11e7-9982-5143bced3920.png)

- **Hibrido**: Estou começando a achar que existe um padrão. Mais uma vez você ficou nervosão com tudo e esqueceu do nosso querido **Híbrido**, hehe

**Comment by hurickkrugner-luizalabs** [comment]
### Slide #14

![image](https://user-images.githubusercontent.com/30271766/35042690-ca62ce0e-fb70-11e7-9e80-e9b7b309ce88.png)

- **Contras**: Não entendo o absurdo que você escreveu aqui dizendo que React Native tem contras. O que foi isso? Acho que você deveria apagar esse seção completa 😂

**Esse post foi brincadeirinha**.

**Comment by hurickkrugner-luizalabs** [comment]
### Slide #37

![image](https://user-images.githubusercontent.com/30271766/35042886-7599d538-fb71-11e7-8aec-5608b25cd947.png)

- **Cases de sucesso**: Acho que pra descontrair um pouco, você poderia adicionar algum aplicativo que tenha feito com Ionic como **case de sucesso**, sabe? Só pra brincar um pouquinho com o pessoal.

**Comment by hurickkrugner-luizalabs** [comment]
Em geral, a construção do slide tá bem legal. Várias imagens ilustrativas, pouco texto (que deixar o slides muito cansativos), descontrações... acho que vai ser bem maneiro.
A parte do slide tá feita, agora só depende de você na apresentação! 😉

Bom, foi isso que eu levantei que achei relevante comentar. Espero que tenha ajudado em algo.
Good luck, my friend 🍀

**(Agora tá liberado pra comentar)**

**Comment by juninmd** [comment]
Manim, muito obrigado por suas colaborações, já fiz um novo commit para ajustar esses itens.

Novamente, muito obrigado!

**Comment by hurickkrugner-luizalabs** [comment]
@juninmd magina, cara. No que eu puder ajudar, pode ter certeza que estou aqui :)
Fica em paz e, novamente, boa sorte!
